# Generated by rust2rpm 27
%bcond check 1

Name:           rs_dfu
Version:        0.7.0
Release:        %autorelease
Summary:        USB Device Firmware Upgrade (DFU) implementation based on nusb crate

License:        MIT
# LICENSE.dependencies contains a full license breakdown

URL:            https://github.com/EdgeTX/rs-dfu
Source:         https://github.com/EdgeTX/rs-dfu/archive/refs/tags/v%{version}.tar.gz#/rs-dfu-%{version}.tar.gz

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
%{summary}.}

%description %{_description}

%prep
%autosetup -n rs-dfu-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%doc README.md
%{_bindir}/rdfu

%changelog
%autochangelog
