# Generated by rust2rpm 28
%bcond check 1
%global debug_package %{nil}

%global crate nusb

Name:           rust-nusb
Version:        0.2.1
Release:        %autorelease
Summary:        Cross-platform low-level access to USB devices in pure Rust

License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/nusb
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          nusb-fix-metadata-auto.patch

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Cross-platform low-level access to USB devices in pure Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+smol-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+smol-devel %{_description}

This package contains library source intended for building other packages which
use the "smol" feature of the "%{crate}" crate.

%files       -n %{name}+smol-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
