
name: EdgeTX Companion rpm

on:
  push:
  pull_request:
  schedule:
    - cron: '23 2 1 * *'
  workflow_dispatch:
    inputs:
      fedora:
        description: Fedora version
        type: string
        default: latest

jobs:
  build:
    name: Build on Fedora
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: mkdir dependencies/rpms
      - run: podman build --security-opt label=disable -v $(pwd)/dependencies/rpms:/root/rpmbuild/RPMS --build-arg=PACKAGE=rust-nusb -f dependencies/Dockerfile .
      - uses: actions/upload-artifact@v6
        with:
          name: rust-nusb-rpms
          path: dependencies/rpms/**/rust-nusb*.rpm
      - run: podman build --security-opt label=disable -v $(pwd)/dependencies/rpms:/root/rpmbuild/RPMS --build-arg=PACKAGE=rust-nonempty -f dependencies/Dockerfile .
      - uses: actions/upload-artifact@v6
        with:
          name: rust-nonempty-rpms
          path: dependencies/rpms/**/rust-nonempty*.rpm
      - run: podman build --security-opt label=disable -v $(pwd)/dependencies/rpms:/root/rpmbuild/RPMS --build-arg=PACKAGE=rs_dfu -f dependencies/Dockerfile .
      - uses: actions/upload-artifact@v6
        with:
          name: rs_dfu-rpms
          path: dependencies/rpms/**/rs_dfu*.rpm
      - name: Build source container image
        run: podman build -t localhost/edgetx-builder -f .github/Dockerfile .
      - run: mkdir -p rpmbuild/SRPMS
      - name: Build the srpm
        run: podman run --rm --name edgetx-builder -v $(pwd)/rpmbuild:/root/rpmbuild:Z --network=none localhost/edgetx-builder bash -c '( rpm -Uvh *.src.rpm && rpmbuild -bs ~/rpmbuild/SPECS/*.spec ) || ( cp *.src.rpm ~/rpmbuild/SRPMS/ && exit 1 )'
      - run: find rpmbuild/SRPMS
      - run: |
          srpm_path=$( find rpmbuild/SRPMS -type f )
          echo "srpm_path=$srpm_path" >> $GITHUB_ENV
          echo "srpm_name=$( basename $srpm_path )" >> $GITHUB_ENV
        if: always()
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.srpm_name }}
          path: ${{ env.srpm_path }}
        if: always()
      - name: Build the rpm
        run: podman run --rm --name edgetx-builder -v $(pwd)/rpmbuild:/root/rpmbuild:Z --network=none -e CMAKE_OPTS='-DCMAKE_VERBOSE_MAKEFILE:BOOL=OFF' localhost/edgetx-builder bash -c 'rpm -Uvh ~/rpmbuild/SRPMS/*.src.rpm && rpmbuild -bb ~/rpmbuild/SPECS/*.spec'
      - run: find rpmbuild/RPMS
      - run: |
          rpm_path=$( find rpmbuild/RPMS -type f | grep -v debug )
          echo "rpm_path=$rpm_path" >> $GITHUB_ENV
          echo "rpm_name=$( basename $rpm_path )" >> $GITHUB_ENV
        if: always()
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.rpm_name }}
          path: ${{ env.rpm_path }}

